### ISSUE TITLE
Access to GuillotineMenuViewController

### ISSUE THREAD

**Issue by glancashire** [Yalantis/GuillotineMenu#13]
Dear Yalantis

Thanks for your excellent control.

I have integrated it into my Swift Project. However the compiler complained that GuillotineMenuViewController is undeclared.

To be able to compile successfully, I had to change the access in GuillotineMenuViewController.swift to public, e.g.

public class GuillotineMenuViewController: UIViewController {

instead of 

class GuillotineMenuViewController: UIViewController {

In addition some of the routines and properties should also be public.

Kind Regards
Graham

**Comment by Aymenworks** [comment]
Hello. I didn't encountered this problem.
Maybe you forgot to add the Guillotine menu in your target ?
Try to click on the swift files and in the File Inspector ( left in Xcode ), see if he target is checked

**Comment by glancashire** [comment]
I have used cocoapods to integrate it and it is a swift project, so target etc should be set correctly.
Maybe it is the combination of cocoapods + swift that causes problems.

However by putting public it is easy to fix.

kind regards
graham
