### ISSUE TITLE
Objective-C Version

### ISSUE THREAD

**Issue by taglia3** [Yalantis/GuillotineMenu#15]
Have you plan to code an Objective-C version of this great control?

Thanks,
Matteo

**Comment by maksym-letiushov** [comment]
Hi @taglia3 
Currently we don't have any plans to provide a separate version in Objective-C.
We are preparing a new version of GuillotineMenu with significant changes and will check whether menu can be used from objective-c code.

**Comment by taglia3** [comment]
Hi @maximletushov 
I've created an objc version of this great control!
Check out my version on Github: https://github.com/taglia3/GuillotineMenu-Yalantis-objc-version
