### ISSUE TITLE
Speeding  up animation 

### ISSUE THREAD

**Issue by WillemPieterse** [Yalantis/GuillotineMenu#2]
Hi there,

I love your menu! I am trying to use it in my IPAD only app. The animation is very slow in this case. I have tried setting : 
private let duration = 0.6 
Had no impact. Please give me an indication how to speed up the animation?

**Comment by maksTheAwesome** [comment]
Hello, Willem.
Thank you for your interest to our menu. In out case the animation duration does not define animation speed. To make menu move faster you should find the private let vectorDY: CGFloat = 1500 and set larger number for it. It'll increase force moving the menu and as result will speed it up.
