### ISSUE TITLE
Device orientation causes frustration 

### ISSUE THREAD

**Issue by support3ds** [Yalantis/GuillotineMenu#22]
The screen orientation is set to Portrait and Upside Down.

After the release of swift 2.2 a minor bug has been monitored.

If i open the app holding the device as "portrait" it works as expected.
If i open the app holding the device as "landscape" the menu behaves like pendulum.

I've tested it also in your example, by changing only the screen orientation of your example "GuillotineMenuExample"

**Comment by Vodolazkyi** [comment]
Thanks for your comment, this issue fixed and will be in new release v3.0.1
