### ISSUE TITLE
iOS 7

### ISSUE THREAD

**Issue by pjebs** [Yalantis/GuillotineMenu#26]
I don't have an iOS 7 device or simulator but my app must support iOS 7 min.

What part of code base stops it from being compatible with iOS 7. I don't seem to see anything that is iOS 8+

**Comment by pjebs** [comment]
Since you're more likely to have an iOS 7 device can you please check if it "seems to work"? No fancy tests. Just enough to know it does or doesn't crash immediately.

**Comment by pjebs** [comment]
@serejahh can you help me out?

**Comment by serejahh** [comment]
Hi @pjebs. Sorry for my late reply
iOS 7 doesn't support dynamic frameworks. That's the reason of minimal target. Sure, you can find a workaround, but there's no guarantee it will work properly all the time

**Comment by pjebs** [comment]
If that's the case, although it can't be used with cocoapods, you should write on the documentation that it can be used by manually adding the files to an iOS 7+ project.
