### ISSUE TITLE
After Animation UI doesn't respond for 1-2 seconds

### ISSUE THREAD

**Issue by dingua** [Yalantis/GuillotineMenu#3]
After that animation is finished in the two modes : Presentation & Dismissal , the UI doesn't respond :
- you can not select anything ..for example for the demo application you can not neither select the menu button nor scrolling the tableView.

**Comment by dingua** [comment]
if you remove "elasticity" animation of "UIDynamicItemBehavior" (GuillotineTransitionAnimation  class line #124)
and you move "animationContext.completeTransition" from "dynamicAnimatorDidPause" to "collisionBehavior :  beganContactForItem:  withItem:, atPoint :"
this will be resolved but the elasticity animation will be removed.

**Comment by maksTheAwesome** [comment]
sorry for long time no reply. you can add the itemBehaviour.resistance = 0.5 around line 123 in the GuillotineTransitionAnimation.swift file. This should fix the problem. Unfortunately I did not reproduce the bug. Let me know how did it work for you.

**Comment by ghost** [comment]
@maksTheAwesome - I just tried it, and i did not work. In line #124 the code already is there with "1" and not 0.5. I tried changing it, but it did not work.

**Comment by mrcompoteee** [comment]
The new version of GuillotineMenu (2.0.1) is available. Feel free to check it out!

**Comment by alabib** [comment]
The issue still exist , Please reopen the issue.

**Comment by sergey-prikhodko** [comment]
The new version of GuillotineMenu (4.0) is available. Feel free to check it out!
