### ISSUE TITLE
Dismiss animation is not fast enough

### ISSUE THREAD

**Issue by BadReese** [Yalantis/GuillotineMenu#32]
when i set animationDuration lower than 0.15, dismiss animation will never stop. How could I make animation faster and without dismiss bug?

thank you.

**Comment by the-freshlord** [comment]
I have actually experienced this as well. It also shakes the navigation bar.

**Comment by BadReese** [comment]
@eman6576  em.. so how you fix it?

**Comment by edBaev** [comment]
@serejahh

**Comment by BadReese** [comment]
@edBaev  haha, you saw my email?

**Comment by serejahh** [comment]
@BadReese Thanks for reporting the issue. I'm trying to solve it

**Comment by BadReese** [comment]
@serejahh hey, have you fixed the bug?

**Comment by Vodolazkyi** [comment]
https://github.com/Yalantis/GuillotineMenu/issues/36
