### ISSUE TITLE
When adding constrain on button on menu controller in ios 10 , menu goes down

### ISSUE THREAD

**Issue by swatirahane17** [Yalantis/GuillotineMenu#34]
i use guillotineMenu in my application, it's work fine before ios 9, but when i try my application on ios 10,my menu item goes down. This problem comes when only i aaply constrain on my menu items. If i remove all constrain it works fine.  my menu looks like below image url-
https://mail.google.com/mail/?ui=2&ik=b52cec5c23&view=fimg&th=15779dcf62a6d650&attid=0.1.3&disp=emb&attbid=ANGjdJ9ikGsbkM_xZhUJbIj61Ev2392UL5SyHA7xeI9oC7UlsMKAL6damrcsVs_j7U5ZzeG4JyaVmLt_V6DEJaTeU5ChW3fzlEluLq-UoGeW36Yn1vXDv4KqzivAzyw&sz=s0-l75-ft&ats=1475487755862&rm=15779dcf62a6d650&zw&atsh=1

**Comment by riyal123** [comment]
facing the same issue in iOS 10

**Comment by serejahh** [comment]
Hi @swatirahane17! The link is unavailable. Could you attach an image here?
