### ISSUE TITLE
duration time and spring effect!

### ISSUE THREAD

**Issue by XOneto9** [Yalantis/GuillotineMenu#36]
1) I find to adjust my project of speed duration time.
But If I'am change the time from 0.6 to 0.1, then simulator got a some bug at disappear page to up side. not remove completely.

so, what should I change time to 0.1 how can I do?

2) second I can not find spring effect part!
could please where is that?

I feel the effect of spring effect so much..

**Comment by Bliss00** [comment]
1. Just change it in your calling ViewController as presentationAnimator.animationDuration = 0.1
2. It is already implemented. However, when you speed up it to 0.1, it becomes too fast, so that it may seem, it is not there.

**Comment by Vodolazkyi** [comment]
Hi, this problem is solved in the new version 3.0.1
