### ISSUE TITLE
iPhone 6S leaning screen

### ISSUE THREAD

**Issue by Darkkrye** [Yalantis/GuillotineMenu#37]
Hi !

I have exactly the same problem than this : https://github.com/Yalantis/GuillotineMenu/issues/17

But I use Xcode 8 and an iPhone 6S with iOS 10.1.1. The Example project works but I don't know why in my project it does not works. 
It stops after `willStartPresentation`.

Thank you for your help !

**Comment by Saulenco** [comment]
do you use the `UITableViewController` as Menu ?

**Comment by Darkkrye** [comment]
No, I use a simple `ViewController`as a Menu.

**Comment by srj0x0** [comment]
@Darkkrye Hello, thank you for report! Please, describe your problem in more detail.
