### ISSUE TITLE
Menu UIButton -> UIBarButtonItem

### ISSUE THREAD

**Issue by dcarriola** [Yalantis/GuillotineMenu#39]
I tried to add the GuillotineMenu to my app but i saw the menu button inside the menu view never appears because it returns an UIButton in the dismissButton variable and the button in the navigation bar is an UIBarButtonItem. I don't know if it's something i have to change or is something from a newer version of Xcode because i couldn't have access to the button within the uibarbuttonitem in the storyboard. I even had to change the code in the viewcontroller when i want to present the menu (presentationAnimator.presentButton = sender.customView as? UIButton) because the sender is an UIBarButtonItem.

Please let me know about this issue. If i must change something on my side or it's something different.

Thanks!

### Your Environment

- [X ] Version of the component: latest
- [X ] Swift version: 3
- [X ] iOS version: 10.2
- [X ] Xcode version: 8.2.1 (8C1002)

**Comment by Vodolazkyi** [comment]
Hi, did you check our example ?

**Comment by bitw14** [comment]
just drag UIButton to Navigation bar  ..

**Comment by Saulenco** [comment]
You can use the UIBarButtonItem as follow:
```
let menuButton = UIButton()
//.... your button settings
menuButton.addTarget(self, action: #selector(self.buttonShowMenuPress(_:)), for: .touchUpInside)
let menuItem = UIBarButtonItem(customView: menuButton)
self.navigationItem.leftBarButtonItem = menuItem
```
