### ISSUE TITLE
Change view from menu

### ISSUE THREAD

**Issue by RpX974** [Yalantis/GuillotineMenu#4]
Hi :),

Thank you for your menu, it's so cool ^^.
But I don't understand something, how do you do to change view from the menu (from profile button by example) ?
May be i'm too tired lol but i tried all, and nothing works ...
Can you help me ?
Thank you.

**Comment by Andysunxs** [comment]
这个功能不是我写的 你可以看到这个菜单的作者

**Comment by adnangumus** [comment]
I didn't find any way to solve this issue. Can you please update your example with segue to other viewcontrollers.
thank you.

**Comment by DanielSmith1239** [comment]
I am also having this issue. Can someone please help?

**Comment by andreaseid** [comment]
The best way (for me) is to change the content of the viewcontroller.

Create some Content-XIB for every activity.
With the IBAction connected at the Menu-Button, you can set a view of the Main-ViewController with the XIB content. 

I hope understand, if not I will make you a more concrete example these days . (currently i'm very busy at work . )

**Comment by maksTheAwesome** [comment]
Hello everyone. Thank you for trying out our menu.

I'm sorry for missing that part. To fix it you will have to make changes in the GuillotineMenuViewController and your Host View controller. You will need to add delegate method that will let your host VC know what button was tapped on the guillotine menu and add actions in those delegate methods.

I'm busy with the project now and will update the menu as soon as I will have some free time. If you do not want to wait we are free for pull requests.

**Comment by DanielSmith1239** [comment]
Thank you. Do you know how long until you post it? I really need your help.

**Comment by lilpennyjr** [comment]
I second this. I'm not exactly following how to do this. Maybe creating one using "Profile" that pushes to a different view controller would help. Thanks!

**Comment by wobenzym** [comment]
Well this is what I'm doing:

``` java
switch (v.getId()) {
                    case R.id.gPocetna:

                        gPocetna.setTextAppearance(getApplicationContext(),R.style.TextView_GuillotineItem_Selected);
                        gSS.setTextAppearance(getApplicationContext(),R.style.TextView_GuillotineItem);
                        gPocetna.setTypeface(type);
                        gSS.setTypeface(type);
                        gb.close();

                        final Handler handler1 = new Handler();
                        handler1.postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                //Do something after 100ms
                                new setFragment(new HomeFragment(),"HomeFragment").execute();
                            }
                        }, 350);
                        flag = 1;

                        break;
```

Changing the fragment inside the container when the animation ends(350ms in my case)

**Comment by mrcompoteee** [comment]
The new version of GuillotineMenu (2.0.1) is available. Feel free to check it out!
