### ISSUE TITLE
Not Working with UITabBarController

### ISSUE THREAD

**Issue by agahii** [Yalantis/GuillotineMenu#45]
i want to implement this liabrary with my tabview controller , but i couldnt 
facing following error 
<img width="827" alt="screen shot 2017-05-14 at 10 53 04 pm" src="https://cloud.githubusercontent.com/assets/3959154/26036504/54c37de6-38f8-11e7-9608-4bfbbceacd05.png">

**Comment by bitw14** [comment]
do this... 
extension TabBarViewController : UIViewControlelrTransitioningDelegate {



}

**Comment by Saulenco** [comment]
as @bitw14  said add de TransactionDelegate you your TabController , use the sample project.
I also using this with tabController and just add the delegate :
```
extension YourTabController: UIViewControllerTransitioningDelegate {
    
    func animationController(forPresented presented: UIViewController, presenting: UIViewController, source: UIViewController) -> UIViewControllerAnimatedTransitioning?{
            presentationAnimator.mode = .presentation
            return presentationAnimator
    }
        

    func animationController(forDismissed dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning?{
        presentationAnimator.mode = .dismissal
        return presentationAnimator
    }
}
```
