### ISSUE TITLE
Use of unresolved identifier in ViewControllerTransitioningDelegate

### ISSUE THREAD

**Issue by joshharington** [Yalantis/GuillotineMenu#46]
# Report

> I copied the code from the example project and it won't run. The example project will run though. So Basically it is saying that there is errors of "use of unresolved identifier presentationAnimator and cellHeight.

<img width="1338" alt="screen shot 2017-05-25 at 6 36 34 am" src="https://cloud.githubusercontent.com/assets/10532582/26436160/d1883e9c-4114-11e7-82dd-014444d18a35.png">

As I said, the example project runs but not the copied code. I have included it in pod file and installed it and imported it. 

What can I do to resolve this?

- [ ] Version of the component: commit 39f8585
- [ ] Swift version: 3
- [ ] iOS version: 10
- [ ] Device: Simulator iPhone 6s
- [ ] Xcode version: 8.3
- [ ] If you use Cocoapods: _run `pod env | pbcopy` and no result
- [ ] If you use Carthage: _run `carthage version | pbcopy` and carthage not installed

**Comment by Saulenco** [comment]
Just pay more attention to variable declaration, I guess you don't copy the variable declaration too.

**Comment by celil** [comment]
Please be sure to add these at viewcontroller class;

`    
fileprivate let cellHeight: CGFloat = 210

fileprivate let cellSpacing: CGFloat = 20

fileprivate lazy var presentationAnimator = GuillotineTransitionAnimation()`
