### ISSUE TITLE
Button changes of position when we push on it

### ISSUE THREAD

**Issue by Hugo75002** [Yalantis/GuillotineMenu#48]
Hello there,

Just to let you know, i have experiencing an issue with the button on the top left corner.
When the first VC appears, the button has a good position, but as soon as i push on it to get the second VC, the button move on the maximum top and left corner...
When i push again to get back on the first VC, the button gets back its correct position...
I ve compared between my version and the example... but i don't find anything...

**Comment by Dhrumil-Dhameliya** [comment]
After installing pod 'GuillotineMenu', '~> 3.0' 

In GuillotineMenuTransitionAnimation.swift file

Replace Function 
func setupContainerMenuButtonFrameAndTopOffset() {
        topOffset = supportView!.frame.origin.y + supportView!.bounds.height
        let senderRect = supportView!.convert(presentButton!.frame, to: nil)
        containerMenuButton?.frame = senderRect
}

With Below Function

func setupContainerMenuButtonFrameAndTopOffset() {
        if let supportView = supportView, let presentButton = presentButton {
            topOffset = supportView.frame.origin.y + supportView.bounds.height
            let presentButtonFrame = presentButton.convert(presentButton.bounds, to: supportView)
            let senderRect = supportView.convert(presentButtonFrame , to: nil)
            containerMenuButton?.frame = senderRect
        }
    }

**Comment by DanielZanchi** [comment]
This solution worked!

**Comment by srj0x0** [comment]
@Hugo75002 Hi, thanks for your report! Please try the latest version of our framework, it should contain a fix for this issue. Let me know if its not.
