### ISSUE TITLE
XCODE 6.3

### ISSUE THREAD

**Issue by WillemPieterse** [Yalantis/GuillotineMenu#5]
Good Day,

I ported my code to XCode 6.3 and got the following error, at runtime:

Could not find a segue class named 'GuillotineMenuSegue'

**Comment by DanielSmith1239** [comment]
I am also getting this issue

**Comment by WillemPieterse** [comment]
Just some feedback, I retested the demo project on Swift 1.2 (XCode 6.3), and the code works flawlessly.

**Comment by DanielSmith1239** [comment]
Thank you. I found my mistake. I had to change the “Segue Module” for the segue to my app.
