### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by alichtman** [Yalantis/GuillotineMenu#50]
###  What did you do?
Opened `Preview` link in README and saw: `Cannot proxy the given URL`

**Comment by rnkyr** [comment]
which exactly link doesn't work? checked all available links in readme and they works fine

**Comment by alichtman** [comment]
> which exactly link doesn't work?

This information is in the only sentence in the bug report.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/20600565/47048872-4980a280-d161-11e8-868b-9c6256b216c8.png">


> **Opened Preview link in `README` and saw: Cannot proxy the given URL**

https://camo.githubusercontent.com/10639e803a90fadd751d3683c497c449e2a48339/68747470733a2f2f6431337961637572716a676172612e636c6f756466726f6e742e6e65742f75736572732f3439353739322f73637265656e73686f74732f323031383234392f64726166745f30362e676966

Here's the link, copied from your README. When I go to this link, I get a page with this error text on it: `Cannot proxy the given URL`.

**Comment by rnkyr** [comment]
> This information is in the only sentence in the bug report.

I'm asking because I don't see any `Preview` links in readme: https://monosnap.com/file/jYtwxa57y5nekFvnmxBqlUeykuJYLH

Ok, got it. Will take a look shortly

**Comment by alichtman** [comment]
Maybe try hosting the image on GitHub in an `img/` directory.
That's always what I do.

**Comment by rnkyr** [comment]
sure, that's the right way. don't know why it made in a different way

**Comment by rnkyr** [comment]
@alichtman, check out the fresh readme. should work now
thank you for pointing on that issue 👍

**Comment by alichtman** [comment]
Looks good now.
