### ISSUE TITLE
not able to navigate back from menu

### ISSUE THREAD

**Issue by dishasyno** [Yalantis/GuillotineMenu#54]
I have added the menu through this code. in the menu view, I have one button to navigate to a second view controller. when I dismiss the second view controller menu dismiss icon is not visible in the menu view controller. Kindly help with this.

**Comment by sergey-prikhodko** [comment]
Hi @dishasyno, you must have two buttons, the first in controller who presented a menu, the second in the menu controller. In our example project: the first button in the navigation of `ViewController`, the second on `MenuViewController`, you can see these buttons in `Main.storyboard`
