### ISSUE TITLE
How to give showmen segue?

### ISSUE THREAD

**Issue by sekhar9989** [Yalantis/GuillotineMenu#56]
It's working with animation like example for me, I think segue didn't given properly in my project.
how to give showmen segue to menu view controller?

**Comment by sergey-prikhodko** [comment]
Hi @sekhar9989, sorry for the late reply. You can present a menu from the segue, for this you have to add segue to menu controller on your storyboard, then you have to realize `instantiation` method for this segue, for example
```swift
@IBSegueAction func prepare(_ coder: NSCoder) -> MenuViewController? {
        let controller = MenuViewController(coder: coder)!
        controller.modalPresentationStyle = .custom
        controller.transitioningDelegate = self
        
        presentationAnimator.animationDelegate = controller
        presentationAnimator.supportView = navigationController!.navigationBar
        presentationAnimator.presentButton = barButton
        
        return controller
    }
```
