### ISSUE TITLE
CococaPods support

### ISSUE THREAD

**Issue by tbaranes** [Yalantis/GuillotineMenu#6]
Hi,

I know it's "coming soon", but do you think to release a pod soon? It will be great to have one.

**Comment by serejahh** [comment]
@tbaranes, you can add our spec directly to your podfile:

```
use_frameworks!
pod 'GuillotineMenu', :git => 'https://github.com/Yalantis/GuillotineMenu.git'
```

**Comment by serejahh** [comment]
@tbaranes Now you can pull it from cocoapods registry. Check out our readme file
