### ISSUE TITLE
converting to objective c

### ISSUE THREAD

**Issue by rohith12** [Yalantis/GuillotineMenu#7]
Can you help me out for converting swift to objective c? I'm new to objective c and swift.

**Comment by Andysunxs** [comment]
我目前就会swift语言

**Comment by georgel** [comment]
+1 :)

**Comment by taglia3** [comment]
+1

**Comment by taglia3** [comment]
Hi

I've created an objc version of this great control!
Check out my version on Github: https://github.com/taglia3/GuillotineMenu-Yalantis-objc-version
